services:
  main_bot:
    build:
      context: .
    env_file:
      - env/main.env
    restart: on-failure
    volumes:
      - ./bot:/bot
    depends_on:
      - postgres_main1809
      - redis_FSM1809

  postgres_main1809:
    image: postgres:16.2
    env_file:
      - env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_FSM1809:
    image: redis:5.0.5
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

